services:
  # Platform Orchestrator API
  orchestrator:
    build:
      context: ../
      dockerfile: docker/Dockerfile.orchestrator
    container_name: midnightos-orchestrator
    env_file:
      - ../platform/orchestrator/.env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../user-data:/app/user-data
    ports:
      - "3002:3002"
    networks:
      - midnightos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Midnight MCP Service
  midnight-mcp:
    build:
      context: ../
      dockerfile: docker/Dockerfile.midnight-mcp
    container_name: midnightos-mcp
    env_file:
      - ../services/midnight-mcp/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - AGENT_ID=midnightos-mcp-001
      - MIDNIGHT_SEED=test-seed-for-docker-development-change-in-production
      - WALLET_SERVER_HOST=midnight-mcp
      - WALLET_SERVER_PORT=3001
      - STORAGE_BASE_DIR=/app/.storage
      - PROOF_SERVER=http://proof-server:6300
    ports:
      - "3001:3001"
    volumes:
      - wallet-storage:/app/.storage
      - mcp-logs:/app/logs
    networks:
      - midnightos-network
    depends_on:
      - proof-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Platform Frontend
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    container_name: midnightos-frontend
    env_file:
      - ../platform/frontend/.env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://orchestrator:3002/api
      - NEXT_PUBLIC_MCP_URL=http://midnight-mcp:3001
    ports:
      - "3003:3003"
    depends_on:
      - orchestrator
      - midnight-mcp
    networks:
      - midnightos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ElizaOS Agent (Default instance)
  eliza-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile.eliza-agent
    container_name: midnightos-eliza-agent
    env_file:
      - ../services/eliza-agent/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MCP_SERVER_URL=http://midnight-mcp:3001
    ports:
      - "3000:3000"
    depends_on:
      - midnight-mcp
    networks:
      - midnightos-network
    restart: unless-stopped
    volumes:
      - eliza-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Proof Server (Required for Midnight Network)
  proof-server:
    image: midnightnetwork/proof-server:latest
    container_name: midnightos-proof-server
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=6300
      - ROCKET_LOG_LEVEL=info
      - RUST_LOG=info
    ports:
      - "6300:6300"
    volumes:
      - proof-server-data:/data
    networks:
      - midnightos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6300/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: midnightos-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - orchestrator
      - midnight-mcp
    networks:
      - midnightos-network
    restart: unless-stopped
    profiles:
      - with-nginx

networks:
  midnightos-network:
    driver: bridge

volumes:
  wallet-storage:
    driver: local
  user-data:
    driver: local
  mcp-logs:
    driver: local
  eliza-data:
    driver: local
  proof-cache:
    driver: local
  proof-server-data:
    driver: local